mimir:
  image: nice/mimir
  command: node /owldin/server.js
  ports:
    - "80:80"
  links:
    - schema
  volumes:
    - ~/code:/code
  volumes_from:
    - data
schema:
  image: nice/ontologies
data:
  image: nice/ld-docker-data
  volumes:
    - /git/
