mimir:
  image: nice/mimir
  command: node /owldin/server.js
  ports:
    - "80:80"
  links:
    - schema
    - raw
  volumes_from:
    - data
raw:
  image: nice/ld-raw
  expose:
    - 80
  volumes_from:
    - data
schema:
  image: nice/ontologies
data:
  image: nice/ld-docker-data
  volumes:
    - /git/
